branches:
  Madurai:
    keywords:
      - MADURAI

  Selvarathnam:
    keywords:
      - SELVARATHNAM
      - USMAN ROAD
      - T NAGAR
      - T.NAGAR

  Tirunelveli:
    keywords:
      - TIRUNELVELI

  Pallavaram:
    keywords:
      - PALLAVARAM
