document_types:
  grn:
    folder: "GRN"
    filename_patterns:
      - "GRN"
      - "GR0"
      - "GOODS"
      - "RECEIPT"

  po:
    folder: "po"
    filename_patterns:
      - "PO"
      - "PURCHASE"
      - "ORDER"

  db:
    folder: "DB"
    filename_patterns:
      - "DEBIT"
      - "DEBIT NOTE"
      - "DB"
      - "db"

  lr:
    folder: "LR"
    filename_patterns:
      - "LR"
      - "LORRY"
      - "LORRY RECEIPT"
      - "CONSIGNMENT"
      - "TRANSPORT"
